### ISSUE TITLE
Please, could you provide some examples?

### ISSUE THREAD

**Issue by gbonline** [glebm/to_spreadsheet#14]
Hi, i'm looking for a solution to make a excel file from my data and i found your gem very usefull. 
I can make the excel file with data i have, but i don't understand how to combine the formatting into the view. I tried with this start on my haml view file:

```
=format_xls 'table.my-table' do
  workbook use_autowidth: true
  format 'th', b: true 
  format 'tr', bg_color: lambda { |row| 'ddffdd' if row.index.odd? }

%table.my-table
  %tr
and more rows.....
```

copied from your example, but it don't works. 

So i ask you if Could you please provide a more detailed and working example to apply the formatting to the table?

thank's in advance
Giorgio

**Comment by rohitpbhore** [comment]
@gbonline did colspan worked for you ?
