### ISSUE TITLE
Styling not working in ERB template 

### ISSUE THREAD

**Issue by rohitpbhore** [glebm/to_spreadsheet#30]
I could able to successfully deliver .xlsx file using this gem. But facing issue while formatting. I have this below ERB template where I am trying to format, but it didn't work. 

results.xlsx.erb 

```
ruby:
  = format_xls 'table.my-table' do
    workbook use_autowidth: true
    format 'th', b: true
    format 'tr', bg_color: lambda { |row| 'ddffdd' if row.index.odd? }
  end

<table id="my-table">
  <tr><td>One</td></tr>
  <tr><td>Two</td></tr>
  <tr><td>Three</td></tr>
  <tr><td>Four</td></tr>
  <tr><td>Five</td></tr>
</table>
```
Thanks in advance @glebm

**Comment by glebm** [comment]
That's not how ruby code is written in ERB.
Try this instead:

```html.erb
<%
  format_xls 'table.my-table' do
    workbook use_autowidth: true
    format 'th', b: true
    format 'tr', bg_color: lambda { |row| 'ddffdd' if row.index.odd? }
  end
%>

<table id="my-table">
  <tr><td>One</td></tr>
  <tr><td>Two</td></tr>
  <tr><td>Three</td></tr>
  <tr><td>Four</td></tr>
  <tr><td>Five</td></tr>
</table>
```

**Comment by rohitpbhore** [comment]
apologize for the silly mistake.

**Comment by biju-mouli** [comment]
> That's not how ruby code is written in ERB.
> Try this instead:
> <%
>   format_xls 'table.my-table' do
>     workbook use_autowidth: true
>     format 'th', b: true
>     format 'tr', bg_color: lambda { |row| 'ddffdd' if row.index.odd? }
>   end
> %>
> 
> <table id="my-table">
>   <tr><td>One</td></tr>
>   <tr><td>Two</td></tr>
>   <tr><td>Three</td></tr>
>   <tr><td>Four</td></tr>
>   <tr><td>Five</td></tr>
> </table>

I tried this exact same code - I get the spreadsheet without any colors anywhere! Please help!
