### ISSUE TITLE
Error in Range

### ISSUE THREAD

**Issue by argami** [glebm/to_spreadsheet#33]
https://github.com/glebm/to_spreadsheet/blob/4c08455646dd18de51cc1ec05717fbb240c78a68/lib/to_spreadsheet/rule/format.rb#L21

Shouldn't be selector_query instead of selector_type in range_match?

**Comment by glebm** [comment]
It does seem like it. Does changing it fix your issue? If so, please send a PR! :+1:

**Comment by argami** [comment]
Finally my issue was not related with that, but anyways just contributing with a PR.

Thanks!!
